### ISSUE TITLE
libti.googlesignin.a

### ISSUE THREAD

**Issue by jatinj** [hansemannn/titanium-google-signin#6]
I tried to compile the app after adding the module and I got the following error:

[ERROR] :  Module ti.googlesignin version 1.1.3 is missing library file: /Users/jatinjoshi/Documents/Appcelerator_Studio_Workspace/RailGuard/modules/iphone/ti.googlesignin/iphone/libti.googlesignin.a

**Comment by nir777** [comment]
tried your module... buy GoogleaddEventListener('login')  listener not working...  Google.addEventListener('error') too not returns anything...

**Comment by hansemannn** [comment]
Ok guys, so first of all these are two different issues. For @nir777, it has to be a configuration issue, since it's validated and unit-tested to be working when configured correctly. For @jatinj, ensure that `<project-dir>/modules/iphone/ti.googlesignin/1.1.3/libti.googlesignin.a` exists and download the latest release from here if it doesn't.
